---
title: 'Tidy Tuesday #2'
author: "Talia"
output: 
  html_document:
    df_print: paged
    code_download: true
    theme: cerulean
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, error=TRUE, message=FALSE, warning=FALSE)
```

```{r libraries}
library(tidyverse)     
library(lubridate)    
library(ggthemes)     
theme_set(theme_minimal()) 
```

```{r}
# Read in the data for the week
summary <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2021/2021-06-01/summary.csv')
challenges <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2021/2021-06-01/challenges.csv')
castaways <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2021/2021-06-01/castaways.csv')
viewers <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2021/2021-06-01/viewers.csv')
jury_votes <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2021/2021-06-01/jury_votes.csv')
```

This week's data is about the TV show Survivor. Read more about it, including definitions of variables, [here](https://github.com/rfordatascience/tidytuesday/blob/master/data/2021/2021-06-01/readme.md). PLEASE take a moment to read the message at the top about alt text. 

## Graph 

```{r}
challenges %>%
  filter(season == 40) %>%
  group_by(winners) %>%
  summarise(nwins = n()) %>%
  ggplot(mapping = aes(x = reorder(winners, nwins), 
                       y = nwins, 
                       fill = nwins)) + 
  geom_col() +
  theme(legend.position = "none") + 
  labs(x = NULL, 
       y = NULL, 
       title = "Cumulative Times Each Player Won in Season 40 of Survivor", 
       caption = "Plot created by Talia, data from Challenges") + 
  coord_flip()
```