---
title: "Tidy Tuesday Week 29"
author: "Talia"
date: "7/13/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)     
library(lubridate)     
library(ggthemes)      
library(ggalt)
library(ggtext)
library(ggplot2)
library(lubridate)
library(waffle)
theme_set(theme_minimal())
```

```{r}
scoobydoo <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2021/2021-07-13/scoobydoo.csv')
```


```{r}
scoobydoo %>%
  filter(season %in% c("1", "2", "3", "4")) %>% 
  group_by(season) %>% 
  mutate(totengagement = as.numeric(engagement)) %>% 
  ggplot(mapping = aes(x = totengagement, 
                       y = imdb,
                       color = season)) + 
  geom_point() +
  scale_y_discrete(breaks = c(4,5,6,7,8,9)) +
  scale_color_viridis_d() +
  labs(x = "Total Engagement", 
       y = "IMDb Rating",
       color = "Season",
       title = "**HOW MANY PEOPLE WATCHED SCOOBY DOO TV SERIES?**",
       caption = "Plot created by Talia, data from Kaggle Scooby Doo") + 
  theme(plot.title.position = "plot",
        plot.title = element_markdown(family = "mono"),
        plot.caption.position = "plot")
```